name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: RahsyaBenova
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Generate Snake Animation as SVG
        uses: Platane/snk@v2
        with:
          github_user_name: RahsyaBenova
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/*.gif dist/*.svg
          git commit -m 'Generate snake animation'
          git push
